[package]
name = "gui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.31.1", features = [
    "default"
] }
reqwest = { version = "0.12.22", features = ["blocking"] }
rss = "2.0.12"